### ISSUE TITLE
Application failed because default domain is not cluster.local

### ISSUE THREAD

**Issue by nichochen** [flix-tech/vagrant-kubernetes#15]
The default kubernetes domain is set to k8s.local. This cause a lot of troubles to deploy other applications. Because quite a lot of applications use cluster.local to access services.

Will it make sense to change the default domain to cluster.local for better compatibility?

**Comment by hanikesn** [comment]
Sounds reasonable to me. The new version is also more flexible so people can still overwrite it if they want.
