### ISSUE TITLE
Issue with Syntax

### ISSUE THREAD

**Issue by bbethell** [flix-tech/vagrant-kubernetes#6]
There was an error loading a Vagrantfile. The file being loaded
and the error message are shown below. This is usually caused by
a syntax error.

Path: C:/Users/bbethell/.vagrant.d/boxes/flixtech-VAGRANTSLASH-kubernetes/1.6.4/virtualbox/Vagrantfile
Line number: 0
Message: Errno::ENOENT: No such file or directory - vboxmanage --version

**Comment by bbethell** [comment]
New Issue now instead....

Virtual box version is too old, even though it is on 5.1

**Comment by hanikesn** [comment]
@bbethell What does `vboxmanage --version` say?

**Comment by bbethell** [comment]
Hi,

it says error while loading shared libraries: VBoxRT.dll no such file or directory?

I have VBoxManage in my vagrant/bin directory

Thanks

Billy

-------- Original message --------

**Comment by matthewvalimaki** [comment]
I experienced the same issue when upgrading box from `1.5.1` to `1.6.4`. On Windows 10 I would get the exact same error that @bbethell got. When I tried `vboxmanage` on PowerShell it said no such command. Once I added VirtualBox installation to `Path` and restarted PowerShell everything worked fine. I am not sure what fixed it.
